### PR TITLE
Added metrics module to configure MSMB

### PR DESCRIPTION
**Pull request by keithsharp**
I realise that you can do this using the newer OneViewClient module, but my code still uses the older API and it would be useful to me to support configuring the metrics bus.

### CODE REVIEW

**Comment by marikrg** [comment]
Why are you not able to use the new implementation, which uses the OneViewClient?

**Comment by keithsharp** [comment]
I'm adding metrics support to an existing project which uses the old style and I don't want to rewrite that code or end up with a mixed codebase.

**Comment by tiagomtotti** [comment]
Hi Keith, can you please review the following PEP8 issue and ammend the commit ?

hpOneView/metrics.py:50:1: E302 expected 2 blank lines, found 1

Thanks!

**Comment by marikrg** [comment]
Another possibility is use directly the MetricStreaming class from resouces.data_services.metric_streaming (https://github.com/HewlettPackard/python-hpOneView/blob/master/hpOneView/resources/data_services/metric_streaming.py)

**Comment by marikrg** [comment]
I mean, you don't need to use the OneViewClient if you don't want. You can use the MetricStreaming class directly, using the same connection from the legacy SDK. The most breaking difference is that we don't support the blocking parameter and the Task result anymore.

I'm just commenting this to avoid repeated code. If this is the case, let me know and we shall accept the PR.

**Comment by keithsharp** [comment]
How about this plan:

1. Merge this PR as it would be easier for me than to switch to MetricStreaming.
2. Create a new PR that marks the legacy classes as deprecated and bumps the version to 1.0.
3. Tag/Branch and make a release for 1.0.
4. Push 1.0 to PyPi.
5. On the master branch remove all the deprecated classes leaving only OneViewClient.
6. Shortly after OneView 3.0 is released tag/branch and make a release of 3.0.
7. Push 3.0 to PyPi
8. Then at some point in future remove 1.0 from PyPi.

**Pull request merged**
