### PR TITLE
Deprecation warnings

### PR DESCRIPTION
**Pull request by marikrg**

### CODE REVIEW

**Comment by marikrg** [comment]
@danielreed 
We are adding DeprecationWarnings for the legacy modules and documenting it.
Can you give some feedback about the changes?

**Comment by danielreed** [comment]
@marikrg I think the changes in this PR look good, but I had a question about profile.py.  I thought the plan was to support this.  The code in the example server_profiles.py today is very limited.  How would someone configure a server profile with local storage, SAN storage or BIOS?  We need some type of helper/class that someone can use to build those dictionaries.  And I believe there are still users that are using this profile.py file.

**Comment by marikrg** [comment]
> @marikrg I think the changes in this PR look good, but I had a question about profile.py. I thought the plan was to support this. The code in the example server_profiles.py today is very limited. How would someone configure a server profile with local storage, SAN storage or BIOS? We need some type of helper/class that someone can use to build those dictionaries. And I believe there are still users that are using this profile.py file.

We are going to remove the deprecated comments and warning from this specific module and all method from common.py called internally. Later, we should have a call meeting to think how to envolve the dictionary builder support for 2.0 and future versions.

**Comment by marikrg** [comment]
@danielreed  Done!

**Pull request merged**
